### PR TITLE
Linear extrapolation of free boundaries and accompanying unit test

### PR DESCRIPTION
**Pull request by JStewart28**

### CODE REVIEW

**Review by patrickb314 — CHANGES_REQUESTED** [review]
Please guard any print statements and similar things we generally don't want in the main code with ifdefs so that they're not enabled by default. In general, we should just have testcases that test those things (e.g. run 10 timesteps with a known input and compare output with a known output) instead of printing, but includingprints on develop for now as long as they're guarded by an ifdef that defaults to off is okay.

**Comment by JStewart28** [comment]
I will guard print statements with ifdefs going forward. I just ran the update-boundary-conditions code and no stray print statements appeared in rocketrig nor in the test code, run with `make test`.

**Comment by JStewart28** [comment]
I missed the prints in TimeIntegrator. Those have been removed in a later commit.

**Review by patrickb314 — APPROVED** [review]
Approved.

**Pull request merged**
